### ISSUE TITLE
[Issue?] Puller module Mk2 with Refined Storage

### ISSUE THREAD

**Issue by accessdenied0** [desht/ModularRouters#10]
Hello @desht ,

I really like you mod a lot. 
Sadly I maybe to ran into an Issue I tried to use the Item Router to extract with the Puller module Mk2 the results out of the RS - Solderer. I tried different configurations and setups, it didn't work. The Mk1 module worked fine.
BUT maybe I did something wrong or I'm just stupid... here is my setup: http://puu.sh/tsZvR/3cc01ebff5.jpg

I thank you for all help.

access_denied

**Comment by desht** [comment]
Is the solderer sided for extracting items?  When you shift-right-click the puller module on the block you want to extract from, the module also records the side you clicked, and will try to extract from that side.

If that doesn't help, let me know and I'll do some testing (I haven't tried this with Refined Storage yet myself).

(Also, since the router is right beside the solderer in your picture, you don't actually need a Mk2 puller...)

**Comment by accessdenied0** [comment]
Ohhh! You have to advice the module to the actual blocks!
I was thinking the module automatically collects from ALL the Solderers... That is why! So I need for each Solderer a separate one?! Yeah the Solderer is sided, but I just did it wrong...

I have a 2 block high row of Solderer with nearly no space for pipes, that is why I need the Mk2...

I thank you so much... It was all my fault at the end... I'm sorry.

**Comment by desht** [comment]
No worries :)

The Puller mk2 is like the Sender mk2/3 - it pulls remotely from the block you configured it to.  So yeah, you'd need one Puller mk2 for each solderer you want to pull from.  But just the one item router, so it stays nice & compact...
