### ISSUE TITLE
suggestion: run once through on redstone signal

### ISSUE THREAD

**Issue by boneskull** [desht/ModularRouters#115]
Currently when an Item Router is in "redstone pulse" mode, it will run for the _duration of the pulse_.  This requires granular control over the number of ticks in the pulse in order to ensure all of the modules run.  

When an Item Router is in "redstone high/low" mode, it will loop through the modules until the redstone power is removed.  This _also_ requires precise timing, because it stops execution immediately. 

It would be "breaking" to change the behavior to _default_ to only stopping after all modules are executed--even though I think this is probably a more intuitive and nicer experience--but a mode/checkbox which will cause Routers to _always_ complete the execution through the set of modules (if one has begun) would be one way to implement.  Another might just be a config flag.

Currently, using precise timing with redstone pulses can _approximate_ the suggestion in #110, but the behavior I'm asking for here would have applicability to all modules.

If you are interested in this, I could try to send a PR myself if I can understand what exactly should be done.

**Comment by desht** [comment]
> Currently when an Item Router is in "redstone pulse" mode, it will run for the duration of the pulse. 

That is not the case, no.  When a pulse is received, all the modules will run, regardless of the duration of the pulse.  The only limitation is speed upgrades; the router will not run more often than its speed upgrades permit (so you can't use a very fast clock signal to bypass speed limitations).  But once a pulse is received and the router is ready to run, it will execute all its modules in the same tick.

> When an Item Router is in "redstone high/low" mode, it will loop through the modules until the redstone power is removed. This also requires precise timing, because it stops execution immediately.

Again, no. If the router can execute (because it has the right signal), it will execute all its modules on the same tick.  The only thing that would stop a particular module from executing is if it has a Redstone Augment with different settings.

**Comment by boneskull** [comment]
I must be confused, but pretty sure I was seeing behavior where the router would _not_ run through all the modules (and stop somewhere in the middle).  I'll close this for now
