### ISSUE TITLE
Placer module stopped working

### ISSUE THREAD

**Issue by IamStig** [desht/ModularRouters#126]
### Describe your problem, including steps to reproduce it --- I set up a wither spawner a month or 2 back, worked great, Routers placing the wither skeleton heads on the soul sand, went to use it today and not working, seems something has changed. I had the placer module placing skulls to the front, with a blast proof card installed, made over 30 nether stars....now nothing.

I have likely upgraded the mod since it was working.

I did some testing with a new router and placer module and stone brick blocks ...it doesn't place them either

**Comment by desht** [comment]
Placer module is working just fine for me, including wither skulls.

Have you set up any kind of chunk protection (FTB Chunks etc.)?   If so, then you either need to add the `[Modular Routers]` fake player to the allowed list, or add a Security Upgrade (owned by you) to the router.  The former option is cheaper, the latter option is more secure since the router actually runs as you in that case, and you don't need to worry about other players setting up routers to place/break blocks in your territory.

**Comment by IamStig** [comment]
Used security cards ....that fixed it. I am sure it was chunk loaded before when it was working without the security cards ..... well ... reasonably sure. Thanks Desht. Truly loving the mod and learning new abilities ... did not know that the sender could input into block sides until Dire showed it. Very cool

**Comment by XericShrubland** [comment]
I try to solve around 3 hours. Thanks to @desht and fake players work perfect. 
Inventory -> My team -> Settings -> Allow all fake players. Maybe I can help someone.
