### ISSUE TITLE
Sender, Distributor, and Puller Modules respect sidedness

### ISSUE THREAD

**Issue by ninjabunny66** [desht/ModularRouters#130]
Minecraft 1.16.5
Forge 36.1.3
modular-routers-1.16.5-7.4.0-55

Sender, Distributor, and Puller modules all respect sidedness and appear to only use NSEW. With MK1 modules this can be solved by placing the router adjacent to the desired side. With the MK2,3 and Distributor Modules, they cannot place items from the top/bottom directions(Even if placed adjacent as with an MK1)

Example: Trying to create a furnace array with two routers, one pulling items from a chest and distribute them to 8 furnaces and the other to pull from those 8 furnaces and push into a chest. The routers are incapable of pushing/pulling items from the furnace. If the items inserted are valid fuel items (and therefore able to be added from sides instead of top/bottom directions) they successfully insert the fuel.

**Comment by desht** [comment]
Huh?  There's certainly no limitation to NSEW - Mk1 modules are all quite capable of accessing the top & bottom faces of any inventory block.

As for Mk2/Mk3/Distributors, they access the face of the block they're clicked against (the block highlight that's shown when the module is held renders the selected face differently to make it clear where items will be inserted/extracted).  Routers are absolutely capable of inserting items to the top face of a furnace.

So please clarify because I've no idea what you're talking about.

**Comment by ninjabunny66** [comment]
I was unaware of the fact that it inserts from the side that the module is clicked on, the modules all work fine.
