### ISSUE TITLE
Fluid transfer doesn't work properly when using Ender Tank together

### ISSUE THREAD

**Issue by LeeJiyong9999** [desht/ModularRouters#220]
### Describe the bug

When using the Modular Router with the any items in EnderTanks mod, it perceives the capacity of the tank as 32mB instead of 32B
![2024-03-03_01 59 25](https://github.com/desht/ModularRouters/assets/161961858/1858c00d-6a68-4ef1-92af-84ae15478a1c)
![2024-03-03_02 01 20](https://github.com/desht/ModularRouters/assets/161961858/d1d0cb4d-0e82-4aa0-b372-2dab85ef0a2d)

### How to reproduce the bug

Just put Ender Tank or Ender Bucket in buffer of Modular Router

### Expected behavior

I expect Modular Router to be able to store 32B like Ender Tank, but it can only store 32mB.

### Additional details

Modular Routers - 12.1.1
EnderTanks - 1.2
in All the Mods 9 - 0.2.51

### Which Minecraft version are you using?

1.20

**Comment by desht** [comment]
Not a Modular Routers problem, since the Modular Routers block entity just presents the fluid capability that the item presents.

In addition, this works fine for me with an Ender Tank in a router, as you can see here:

![image](https://github.com/desht/ModularRouters/assets/736831/601b6e07-bdeb-42b8-8cbe-7e024b4dd66a)

Jade correctly reports that there's 2 buckets of lava in the Ender Tank that's in my router.
