### ISSUE TITLE
[1.21] [Neoforge] Routers do not recognise Ars Pedestal/Platform inventories

### ISSUE THREAD

**Issue by ffuentesm** [desht/ModularRouters#239]
### Describe the bug

The Ars pedestal is a single inventory display for items. You can place items on it by clicking on it with an item in hand. 
But when using a sender or puller module, they do not recognize the platform's inventory 
![image](https://github.com/user-attachments/assets/1efba6d6-d980-4d60-a86e-68b0adcfc27c)

### How to reproduce the bug

Try to set the sender module to the Pedestal or use a puller module to extract from the platform. 

### Expected behavior

It should set the pedestal as a valid inventory

### Additional details

ars_nouveau-1.21.0-5.0.2-all
modular-routers-13.0.3+mc1.21

### Which Minecraft version are you using?

1.21

**Comment by desht** [comment]
Modular Routers just does a standard capability query on the block for an item handler. A quick check with a debugger shows that the pedestal doesn't have a registered item handler, so that's on Ars Nouveau to support, if the mod author wishes to do so.

(If you're wondering why the vanilla hopper works, it's because the pedestal implements `Container`, so looks like an inventory to vanilla block entities. But mods are under no obligation to support that, and I have no intention of supporting anything other than capability-based item transfer)
