### ISSUE TITLE
XP Vacuum and Essence of Knowledge

### ISSUE THREAD

**Issue by Xiaminou** [desht/ModularRouters#30]
Now that Thermal Expansion has added the Essence of Knowledge is it possible to have the XP Vacuum output that when Thermal Expansion is present. And a config option when multiple different liquid XP are present, I don't know if Essence of Knowledge and Ender IO's liquid XP will be compatible yet, do they work the same?

**Comment by desht** [comment]
Yeah, I will look into getting essence of knowledge supported. I just need to research its mB->xp conversion ratio. 

Right now only the fluid "xpjuice" works, which is used by EnderIO, Openblocks, Reliquary & Cyclic. But of course EnderIO & Openblocks aren't on 1.12.2 yet.  Update: looks like Openblocks is now available!

**Comment by desht** [comment]
https://github.com/CoFH/CoFHCore/blob/1.12/src/main/java/cofh/core/init/CoreProps.java  suggests a mB->xp ratio of 20 mB per XP, which happens to be the same as "xpjuice", so that's handy.  And the fluid registry name is "experience".

So looks like they're different fluids, so not fully compatible.  But they do have the same conversion ratios.

I should also note that I want to support Industrial Foregoing's "essence" fluid too, and I want to come with a way of potentially supporting multiple fluid types together, similarly to how the PneumaticCraft: Repressurized Aerial Interface does it.

**Comment by desht** [comment]
Added in the 3.1.1 release (just uploaded to Curseforge)

**Comment by Xiaminou** [comment]
Hmm, my router still doesn't pickup XP and fluid pipes won't connect to it.
![2018-01-17_15 08 13](https://user-images.githubusercontent.com/8670392/35046946-c938a828-fb98-11e7-8074-0bf631f0d0e8.png)
![2018-01-17_15 08 33](https://user-images.githubusercontent.com/8670392/35046947-c953bc3a-fb98-11e7-9190-137917a5f7a7.png)

**Comment by desht** [comment]
Can I see a screenshot of your router GUI?  And also of the Vacuum Module GUI?

**Comment by Xiaminou** [comment]
![2018-01-17_15 14 10](https://user-images.githubusercontent.com/8670392/35047047-1d4ef0de-fb99-11e7-8b9a-e82d4c908970.png)
![2018-01-17_15 14 11](https://user-images.githubusercontent.com/8670392/35047048-1d66441e-fb99-11e7-9f6e-3f113aff4545.png)
![2018-01-17_15 14 16](https://user-images.githubusercontent.com/8670392/35047049-1d7dad84-fb99-11e7-97f6-c08636851ae5.png)

**Comment by desht** [comment]
Yeah, you need a fluid tank in the buffer for the Vacuum Module to be able to store fluids in it, and for fluid pipes to be able to connect to the router.  A TE Portable Tank will work fine (pretty much anything other than a bucket should work).

**Comment by Xiaminou** [comment]
Oh, I see, I didn't know it worked like that.

**Comment by desht** [comment]
Yep, the router has no fluid storage of its own.
