### ISSUE TITLE
Crash when placing a vacuum module in a modular router

### ISSUE THREAD

**Issue by calloatti** [desht/ModularRouters#36]
### Minecraft Version

1.12.2

### Forge Version

forge-1.12.2-14.23.2.2611-universal.jar

### Mod Version

modular-routers-1.12.2-3.1.2

### Describe your problem, including steps to reproduce it

Single player, placed first router in world, placed vacuum module in router, game crash, trying to load game crashes again

### Any other comments?

https://paste.ee/p/XcEDp

**Comment by desht** [comment]
This looks like the problem here:

``[07:24:51] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.RenderGameOverlayEvent$Text@702f5e7b:
java.lang.NoSuchMethodError: mcjty.theoneprobe.rendering.RenderHelper.renderItemStack(Lnet/minecraft/client/Minecraft;Lnet/minecraft/client/renderer/RenderItem;Lnet/minecraft/item/ItemStack;IILjava/lang/String;)I
	at me.desht.modularrouters.integration.top.ElementModule.render(ElementModule.java:37) ~[ElementModule.class:?]
``

You're running theoneprobe 1.12.2-1.4.21, and I built Modular Routers with TOP 1.12.2-1.4.18.  It doesn't look like the method signature has changed, though, so that's quite odd.

**Comment by desht** [comment]
~~OK, the method signature for ``renderItemStack`` *has* changed in the 1.4.21 version of TOP, and Modular Routers 3.1.2 won't work with it.  If you downgrade to TOP 1.4.20, your problem should be resolved.~~

~~The next Modular Routers release will likely require TOP 1.4.21, but I can't release that yet since McJty hasn't uploaded a Maven artifact for 1.4.21 yet for me to build against.~~

See below

**Comment by desht** [comment]
Scratch the last comment, I've fixed this in Modular Routers.  A 3.1.3 release has been uploaded and should be approved soon.

Update: 3.1.3 approved.  Closing.

**Comment by calloatti** [comment]
Just reporting that now it works. Thank you for fixing it.
