### ISSUE TITLE
Activator module not right clicking items.

### ISSUE THREAD

**Issue by dariusgemini** [desht/ModularRouters#37]
### Minecraft Version
1.12.2
### Forge Version
14.23.2.2651
### Mod Version
1.12.2-3.1.3
### Describe your problem, including steps to reproduce it
Created a test world using Astral Sorcery(1.12-1.8.5) and Modular Routers installed only. Activator module does not seem to be able to right click items into the Starlight Infuser. As I was testing this, it occurred to me that it could easily be a problem with AS, so I installed Extra Utilities, and a mechanical user set to "Activate block with item" worked just peachy. I would like to mention that the Activator Module does seem to work just fine when tilling dirt with a hoe, etc. 
Slightly unrelated, but it doesn't work with armor stands as well. Extra Utilities doesn't either, so you're in good company on that one.
### Any other comments?
I've been playing Sevtech Ages, and this is my first experience with your mod. I just would like to say that it's fantastic! Keep up the great work!

**Comment by desht** [comment]
Hi, thanks for the report and the kind words.

I'm not overly familiar with AS (been meaning to try it out for ages now...), but is it like Thaumcraft in that you need the appropriate research unlocked before you can activate the Infuser? 

It could be that xutils is using the player who placed down the mechanical user as its fake player (not sure, haven't checked), but Modular Routers uses its own fake player object when simulating right-clicks. If some research is needed, then that right-click would fail.

**Comment by dariusgemini** [comment]
You're welcome!
I actually was on my way back to update the bug report, as I realized I wasn't fully clear. :)

You are partially correct in regards to it being similar to Thaumcraft. There is research involved, but the situation is kinda flipped from what you suggest.

The starlight infuser has three steps in its use. 
1) You have to build what amounts to a multiblock surrounding it.
2) You right click it with an item in hand, and that item is placed into it.
3) You right click the block with an AS wand to start the process.

If what you are suggesting was the case, step 3 would fail, but it's step 2 that actually has the problem.
If I insert the item myself, a router will successfully right click it with a wand.
(Step 1 isn't required to right click an item into it.)

If you want to test it yourself, an instance with just AS and MR installed is all that's needed to reproduce.
Place a starlight infuser and a router with an activator module pointed at it. Put any item in the buffer.

I've also thought a bit more about it, and I decided to test MR with a casting basin from Tinker's Construct. The router won't right click an item into it either.

*Edit - slightly more detail.
*Edit edit - a word.

**Comment by dariusgemini** [comment]
Here's some activator module use-cases that only require MR!
All other mods were removed from the instance.

1) Water source block in front of router, with a bottle in the buffer. (Bucket works with fluid module.)
2) Cauldron with or without water, and the appropriate filled or unfilled bucket or bottle of water in the buffer. Fluid module failed as well. 
3) Flint and steel... This one is weird... Will start fires starting four blocks away, then light each block towards the router, until there is a fire directly in front of the router. As long as that adjacent fire is active, no more fires are created. I was actually trying to test lighting TNT. TNT placed against the face of the router fails to light. TNT placed one block away lit. Upon further testing, router stopped lighting blocks four spots away... Like I said. Weird. I doubt you'll be able to reproduce the first part.
4) Empty/Filled jukebox and music disc/no item.
5) Item frames with any item.
6) Shears on leaves/vines. 

Things that worked:
1) End portal frame and eye of ender. 
2) Sapling and bonemeal.
3) Wheat and bonemeal. 
4) Grass block and bonemeal. 
5) Fence gate/lever/button/door/trap door and any item/no item.   
6) Bottle o' enchanting.
7) Shears and sheep.
8) Bucket and cow.
9) Water/Lava bucket. I almost wrote up milk bucket not working, then I realized I was using vanilla mechanics. And that I'm dumb.
11) Mushroom and mycelium.
12) Place-able blocks. Tested with dirt, torches, redstone torches, buttons, redstone, and spawn eggs. I'm not crazy enough to test every block, though.  
13) Pig and saddle. This one actually made me giggle. 
14) Fishing pole and water. This one makes a casting noise, and that's about it. I'm counting that as a success. :)

I'm sure there's something I missed. 
Oooo. Feeding animals. Didn't test that. That's probably outside the scope of your mod in any case. 
Same with curing zombie villagers.

Thanks again for the great mod!

**Comment by desht** [comment]
Yeah, found & fixed a derp with my block activation code.  I've tested against the Casting Basin (a lot easier than setting up a Starlight Infuser :) and with the change I just pushed, it's now working as expected.  I'm pretty certain it'll also fix your Starlight Infuser issue.

If you'd like to test it out, you can use build 11 or later from http://jenkins.k-4u.nl/view/Desht/job/ModularRouters/ - would appreciate any feedback.

Other notes:
* Fluid module won't work on the vanilla cauldron for the same reason that any other mods' fluid pipes don't - the cauldron doesn't expose a fluid handler capability for mods to use.
* Flint & Steel - the router will click a block up to 4 blocks away, same as a player would.  So it will light the furthest block it can initially, and each subsequent time, it will light the next nearest block.  I put TNT next to the router, and it was able to prime the TNT, no problems.  Make sure the module is set to "face level", and "use item" (not "activate block").
* Shears need to be left-clicked and the activator module only does right-clicking.  I'm not inclined to add left-clicking; feels like a too-cheap way of making mob grinders.
* Item frames: don't work right now because the router only looks for living entities.  However, there's no reason not to look for any entity, so I'm adding that as a feature.  Module will need to be in "use item on entity" mode.  And note that, again, only right-clicking (so no removing items from frames).

**Comment by dariusgemini** [comment]
Awesome! I'm sure the Darksoto and the SevTech: Ages crew will be happy to hear that they have an alternative to automating blocks that work like that. There's a weird mod interaction bug between Cyclic and Astral Sorcery that isn't reproducible when just those two are around. /shrug

But I tested it, and it works, just like you've said.  Thanks!

**Comment by desht** [comment]
Fixed in 3.1.4 release.
