### ISSUE TITLE
Router not distributing evenly

### ISSUE THREAD

**Issue by lstrobel** [desht/ModularRouters#41]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2707 (I'm playing Sevtech 3.0.8)

### Mod Version
1.12.2-3.1.5

### Describe your problem, including steps to reproduce it
I have an item router with three different Mk2 Sender Modules in it. The behavior I would expect is for the router to evenly distribute incoming items in a round-robin fashion. However, it instead focusses only on the first module, distributing to mainly that one.

Here are some pictures:
![The setup](https://user-images.githubusercontent.com/12887715/41188017-c1bab378-6b6b-11e8-9605-037a9f50296c.png)

![Configuration](https://user-images.githubusercontent.com/12887715/41188018-c969794c-6b6b-11e8-8b02-720fe0d0d31d.png)

### Any other comments?
It seems this occurs because the items I wish to distribute are trickling in, and each time a new item comes it resets where it distributes them to.

**Comment by desht** [comment]
Yes, that's how the router behaves I'm afraid.  It just executes each module in turn, so if the first module is able to send the item(s), it will, leaving nothing for the others.

I have been considering a Distributor Module, which would allow distribution of items between multiple inventories (with the ability to select round-robin, nearest first, nearest last etc.).  Since it seems like this would be a useful feature, it's likely I'll add it for the next major release.

**Comment by desht** [comment]
Distributor module has been added, will be in upcoming 3.2.0 release.

If you want to test it out now, you can try build 19+ from http://jenkins.k-4u.nl/view/Desht/job/ModularRouters/

**Comment by desht** [comment]
Distributor module available in 3.2.0
