### ISSUE TITLE
FPS lag spikes

### ISSUE THREAD

**Issue by Susjin** [desht/ModularRouters#5]
I got a lot of fps lag when the extruder module is working (placing and removing blocks).

**Comment by desht** [comment]
Need a bit (lot) more info than that...

- What spec PC is your client running on?
- Video settings? (mipmap levels, fancy/fast, render distance...)
- How many routers with extruder modules?
- How many blocks in the router?
- How many speed upgrades?

For the record, a group of 5 routers extruding 9 blocks here on my dev PC (i7 CPU, GTX 760 GPU) causes no FPS drop at all.  Mipmapping is off (a good idea in 1.10.2 in general it seems), but video settings are turned up otherwise.  Fancy graphics, 16 chunk rendering, vsync on, and I get a solid 60 FPS whether the routers are running or not.

**Comment by Susjin** [comment]
Ok, i think the problem is with my map, because i tested in an new blank world and didn't lag, maybe is because i have a lot of stuff in the same place that make it lag

**Comment by desht** [comment]
In your main world (with the FPS drop), do the extruded blocks touch something like EnderIO conduits when they're placed/removed?  That would cause block updates, which might be lag-inducing (although I think newer EnderIO builds are much better for that)...

**Comment by desht** [comment]
Gonna close this one.  Doesn't appear to be Modular Routers specific, and mostly likely due to general slowness of block updates in busy areas in 1.10.
