### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by static7s** [desht/ModularRouters#6]
I'd like to ask for some sort of muffling module. The flinger and extruder at least are kinda loud, and the in-game configs for those sounds/particles dont seem to be working.

**Comment by desht** [comment]
As it happens, I'm planning one for the next release anyway.  So yes: feature request accepted!

**Comment by desht** [comment]
Just tested configs for flinger and extruder effects, and they work fine:

```
    # Play sounds when Extruder Module extends or withdraws
    B:extruderSound=false

    # Play sound & smoke effect when Flinger Module flings an item
    B:flingerEffects=false
```
With these, there are no sounds/particles for the flinger & extruder.  Be aware that these need to be set server-side (since sounds/particle packets need to be send to all nearby clients).  Just setting client-side won't work.

**Comment by desht** [comment]
Muffler Upgrade has been added in v1.2.0, just releases.
