### ISSUE TITLE
Breaker module always break ice

### ISSUE THREAD

**Issue by MokuJinJin** [desht/ModularRouters#76]
### Minecraft Version
1.14.4
### Forge Version
28.2.3
### Mod Version
1.14.4-5.1.4-9
### Describe your problem, including steps to reproduce it

The breaker does not work as intended with ice block if it does not have silk touch.

First test :
Use breaker module, set whitelist (empty) and Direction back.
place an **ice** block on the back, it **break**.

Second test :
Use breaker module with **silk touch**, set whitelist (empty) and Direction back.
place an **ice** block on the back, it **does not break**.

Third test :
Use breaker module, set whitelist (empty) and Direction back.
place a **packed ice** block on the back, it **break**.
place a **blue ice** block on the back, it **break**.

**Comment by maham** [comment]
It's the same for stone, but not for granite. Might be worth looking at.

**Comment by desht** [comment]
This is because the breaker modules matches on the *item* that would be dropped, not on the block itself.  Since breaking ice with no silk touch drops no items, an empty whitelist does in fact match.  Similarly for stone, which drops cobblestone - you can't match with a stone item unless you're using silk touch - but if you match cobblestone it will work. Granite drops itself as an item, which is why that works.

This is actually intended behaviour, although I appreciate it's a bit confusing.  Just remember that the breaker matches on the item dropped, not on the block being broken.

What I could do is add a module GUI toggle to force matching by block instead of item, but that would go into the 1.15 version of the mod - I'm not updating 1.14.4 anymore other than critical bugs.

**Comment by MokuJinJin** [comment]
I understand.

The name "breaker" is confusing.

Can you just rename it like "retriever" ? to eliminate the confusion ?

Is it do-able in 1.14 ?

Your idea for 1.15 may not be if you rename and eliminate the confusion.

**Comment by desht** [comment]
It breaks blocks - it's a breaker :) I won't be renaming, sorry.

**Comment by MokuJinJin** [comment]
Since it's intended, i'm closing the issue, you can keep it for the 1.15 enhancement.

Thanks for your mod, it's very good.
