### ISSUE TITLE
[1.15.2] Missing Recipes

### ISSUE THREAD

**Issue by NielsPilgaard** [desht/ModularRouters#78]
### Minecraft Version
- 1.15.2

### Forge Version
- 1.15.2-31.2.9

### Mod Version
- modular-routers-1.15.2-6.1.0-17

### Describe your problem, including steps to reproduce it
The following items appear to have no recipes currently

- Security Override Cards
- Breaker Modules
- Extruder Module MK1 (MK2 is fine)

**Comment by desht** [comment]
The Security Override card isn't supposed to have a recipe, it's a creative item (although I should probably ditch it in favour of just checking the player's creative mode).

I'll look into the other two cases.

**Comment by desht** [comment]
Build 18 from https://jenkins.k-4u.nl/job/Modular%20Routers%201.14+/ should fix the problem. 

(Recipes were actually registered, just not showing in JEI.  These two modules have a special recipe because they can now be crafted with *any* pickaxe, and they use the breaking properties of that pickaxe, e.g. a Breaker Module must be crafted with a Diamond Pickaxe or modded equivalent if you want to be able to break Obsidian with it).

https://github.com/desht/ModularRouters/commit/e6e886597640745eeccea4e032a8bc1ab52e1e69

**Comment by desht** [comment]
Fixed in 6.1.1 release
