### ISSUE TITLE
Placing Chisels and Bits blocks with extruder module

### ISSUE THREAD

**Issue by Drexl** [desht/ModularRouters#8]
This doesn't seem to work. Could you add this functionality?

**Comment by desht** [comment]
I'll certainly look into it. Probably shouldn't be too hard but I won't have a chance to play with it till next week...

**Comment by Drexl** [comment]
Much appreciated, thank you! ^_^

**Comment by desht** [comment]
I've had a play with this - good news & bad.  Good news: I can now place C&B blocks in the dev version, and that works OK.  Bad news: I have no control over how those blocks are rotated (C&B block rotation is very much an interactive process using shift & mouse-wheel, which I can't see a way of emulating).  Still, at least symmetric blocks place OK now...

I'll do a little more investigation into controlling the rotation, but not making any promises.

**Comment by Drexl** [comment]
Not sure if this is helpful or not, but when you copy a block with a positive chisel design it's default facing becomes the direction you were facing when you copied it. Maybe you can emulate that functionality instead of trying to emulate mouse control? 
I have no idea how it works, but it's a thought.

Thanks for your work on this! \o/ ^_^

**Comment by desht** [comment]
Yeah, worth looking at.

**Comment by desht** [comment]
Well, I've tried quite a few things, without success I'm afraid (attempting to directly emulate a player right-clicking the item failed in some interesting in messy ways).  I can't see a way to do it :(

I will make a new release v soon with the basic block placement functionality, but as mentioned before, only symmetrical blocks are likely to work.  And not even sure about that, since the NBT on C&B items/blocks seems to change in unpredictable ways when they're placed/broken.  (For the record, XUtils2's Mechanical User appears to have similar problems with placing/breaking C&B blocks, and I suspect RWTema is a lot smarter than I am :) )

**Comment by Drexl** [comment]
Haha, so humble. Thanks anyway. I really appreciate it. Even if it only works part of the time that's more than it did before. ^_^

**Comment by desht** [comment]
Version 1.2.4 uploaded, including C&B support.  As mentioned, block rotation is kind of iffy - sometime works, sometimes not so much.  I will see if I can improve on this in future, though...
