### ISSUE TITLE
Feature Request: Left Click w/Tool Module

### ISSUE THREAD

**Issue by papaworld** [desht/ModularRouters#84]
Hi, we have enjoyed Modular Routers since 1.10.2 days, thank you.

I've reviewed a post here from 2018 for a left click module w/tool, which I have been hoping for since 1.12.2, which would make Modular Routers the "go to turnkey" mod. The response thought was requiring energy (RF) to supply power to the Item Router. Autonomous Activator needs power, Mechanial User does not, Click Machine is optional in config. Actually, in a player world energizing would be easy to accomplish... but, as a mod author a pain I'm sure (and not the original intent of the mod). I have a different thought.

I propose using resource-heavy materials for module crafting. Nether Stars as a eternal "power" source like a beacon. Hardened Sword and Pick-axe materials like Diamond or Obsidian. And, maybe, other OverWorld materials/items (anvil).

Item/fluid collect, transport and use is a mainstay for our worlds. Using your mod for xp orb collection is really cool... but, how to dispatch the mobs using a Sword w/enchantments for loot and xp orb drops? Well, have to use one of those mods listed above. Same with the Pick-axe for custom odd-ball use buids for drops and orbs (coal,redstone,lapis,diamond,emerald ores).

I appreciate your re-consideration for a left click w/tool module. Again, superior mod!

**Comment by desht** [comment]
This has been requested before, but it's still not something I'm happy about adding.  It's just OP for something that needs no power to run, even if it's expensive to craft (I know the Mechanical User doesn't need power but... it's OP :-) 

However, I won't close this just yet, because I am considering making routers powered, and some functionality require power to run (by default nothing will change, i.e. stuff that doesn't need power now won't need it in future - but will be configurable so pack devs can make it more expensive if desired).  If/when I do that, I might consider adding this left-click functionality in, and it will cost power by default.

**Comment by desht** [comment]
Next release has an Attack Entity mode in the Activator module, which requires energy by default (150 FE per attack).

If you want to test a dev build, try build 57 from https://jenkins.k-4u.nl/job/Modular%20Routers%201.14+/ (usual disclaimers apply, back up your worlds, don't use on a production server etc...)

**Comment by desht** [comment]
Added in 7.5.0
